### ISSUE TITLE
Hacer un README que describa mejor el proyecto

### ISSUE THREAD

**Issue by juanmafc** [seguijoaquin/taller2-appserver#26]
Tanto la finalidad del mismo como la estructuras

**Comment by diegofk26** [comment]
Si podes juanma revisa el readme que hice y cerra el issue cuando te parezca que esta todo lo que va en la entrega

**Comment by juanmafc** [comment]
Dejo la referencia al commit que hiciste 98916cdb099d1d7ff39d725a57c4b2d3b4d19cb3 y el link que pasaste http://dillinger.io/ para tenerlo a mano.
